### ISSUE TITLE
https question

### ISSUE THREAD

**Issue by elropero** [mediapolis/digitopia-admin#6]
Hey there, I came across something that I wanted to ask about. I've noticed that on Heroku deployments using https, xhr POSTs were failing. Chrome was basically killing the request because of a "mixed content" (`data-endpoint` was http while the site url was https) condition.

I tracked it down to here:
https://github.com/mediapolis/digitopia-admin/blob/master/server/boot/admin.js#L473

And this was instructive:
https://stackoverflow.com/questions/42750347/nodejs-send-https-request-but-get-http

So just wondering, do you see any reason not to simply use the below instead of including the full URL?

`var endpoint = '/api/' + modelPlural;`

Thanks again for this amazing project. It's really been a lifesaver for me.

**Comment by mediapolis** [comment]
Hello,

That should work for most cases but I should probably make it configurable. I should probably identify whatever scheme loopback uses for the mount point of /api/ instead of hard coding it and come up with a mechanism of surfacing that on the client side. I’m traveling for a couple weeks but will look into that when I get back. In the mean time just fork the project and make the change you need to get it running.

Thanks.

-Michael

**Comment by elropero** [comment]
No rush, I already did fork and am up and running. Thanks for the reply!

**Comment by mediapolis** [comment]
Now configurable in options passed to adminBoot

```
var options = {
    'endpoint': 'http://127.0.0.1:3000/api/'
};
```
